version: '3'

services:
  app:
    build:
      context: ./
      dockerfile: Dockerfile
    restart: always
    ports:
      - "1233:1233"
    depends_on:
      - db
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/postgres
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: password
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: password
    volumes:
      - data:/var/lib/postgres
volumes:
  data: